services:
  nginx:
    build: ./nginx
    ports:
      - 8080:80
    depends_on:
      - web

  web:
    build: .
    expose:
      - 5000:5000
    depends_on:
      - redis
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
